sudo: required
services:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_d8f392e673a0_key -iv $encrypted_d8f392e673a0_iv -in multi-k8s-277004-74cf792bc5cd.json.enc -out multi-k8s-277004-74cf792bc5cd.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google.cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    